# Generated by Django 4.2.7 on 2025-11-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0015_alter_agenttemplate_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltemplate',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20),
        ),
        migrations.AddIndex(
            model_name='globaltemplate',
            index=models.Index(fields=['priority'], name='global_temp_priorit_ca716a_idx'),
        ),
    ]
