# Generated by Django 4.2.7 on 2025-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0017_welcomemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_welcome_message',
            field=models.BooleanField(default=False),
        ),
    ]
