# Generated by Django 4.2.7 on 2025-11-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0018_add_is_welcome_message_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_welcome_message',
        ),
        migrations.AlterField(
            model_name='welcomemessage',
            name='content',
            field=models.TextField(help_text='Welcome message text'),
        ),
    ]
