# Generated by Django 4.2.7 on 2025-11-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0019_remove_message_is_welcome_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='welcome_message',
            field=models.TextField(default='🌟 مرحباً بك في صيدليات خليفة! \n👋 نحن سعداء لخدمتك\nيرجى اختيار نوع الخدمة المطلوبة:\n1 شكوى أو استفسار\n2 طلب أدوية\n3 متابعة طلب سابق\nيرجى الرد برقم الخيار المطلوب (1، 2، أو 3) 📝'),
        ),
        migrations.DeleteModel(
            name='WelcomeMessage',
        ),
    ]
