# Generated by Django 4.2.7 on 2025-11-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0020_systemsettings_welcome_message_delete_welcomemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='perm_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='perm_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='perm_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='perm_medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='perm_no_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('admin', 'Admin'), ('qa', 'QA (Quality Assurance)'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('agent_supervisor', 'Agent Supervisor')], max_length=20),
        ),
    ]
